import { Track, Artist } from '../types';

export const MOCK_TRACKS: Track[] = [
  {
    id: '1',
    title: 'Ambient Beauty',
    artist: 'Aurora Waves',
    artistId: 'artist1',
    duration: 360,
    coverUrl: 'https://picsum.photos/300/300?random=1',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    genre: 'Ambient',
  },
  {
    id: '2',
    title: 'Electric Dreams',
    artist: 'Neon Lights',
    artistId: 'artist2',
    duration: 245,
    coverUrl: 'https://picsum.photos/300/300?random=2',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    genre: 'Electronic',
  },
  {
    id: '3',
    title: 'Sunset Horizon',
    artist: 'Aurora Waves',
    artistId: 'artist1',
    duration: 280,
    coverUrl: 'https://picsum.photos/300/300?random=3',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    genre: 'Ambient',
  },
  {
    id: '4',
    title: 'Midnight Pulse',
    artist: 'Synthetic Echo',
    artistId: 'artist3',
    duration: 220,
    coverUrl: 'https://picsum.photos/300/300?random=4',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    genre: 'Synthwave',
  },
  {
    id: '5',
    title: 'Urban Rhythm',
    artist: 'City Beats',
    artistId: 'artist4',
    duration: 210,
    coverUrl: 'https://picsum.photos/300/300?random=5',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    genre: 'Hip-Hop',
  },
  {
    id: '6',
    title: 'Cosmic Journey',
    artist: 'Aurora Waves',
    artistId: 'artist1',
    duration: 320,
    coverUrl: 'https://picsum.photos/300/300?random=6',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    genre: 'Ambient',
  },
  {
    id: '7',
    title: 'Neon City',
    artist: 'Neon Lights',
    artistId: 'artist2',
    duration: 235,
    coverUrl: 'https://picsum.photos/300/300?random=7',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    genre: 'Electronic',
  },
  {
    id: '8',
    title: 'Digital Echoes',
    artist: 'Synthetic Echo',
    artistId: 'artist3',
    duration: 265,
    coverUrl: 'https://picsum.photos/300/300?random=8',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    genre: 'Synthwave',
  },
  {
    id: '9',
    title: 'Groove Factory',
    artist: 'City Beats',
    artistId: 'artist4',
    duration: 195,
    coverUrl: 'https://picsum.photos/300/300?random=9',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    genre: 'Hip-Hop',
  },
  {
    id: '10',
    title: 'Ocean Waves',
    artist: 'Nature Sounds',
    artistId: 'artist5',
    duration: 420,
    coverUrl: 'https://picsum.photos/300/300?random=10',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    genre: 'Ambient',
  },
  {
    id: '11',
    title: 'Starlight',
    artist: 'Neon Lights',
    artistId: 'artist2',
    duration: 290,
    coverUrl: 'https://picsum.photos/300/300?random=11',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    genre: 'Electronic',
  },
  {
    id: '12',
    title: 'Retro Vibes',
    artist: 'Synthetic Echo',
    artistId: 'artist3',
    duration: 240,
    coverUrl: 'https://picsum.photos/300/300?random=12',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    genre: 'Synthwave',
  },
  {
    id: '13',
    title: 'Beat Drop',
    artist: 'City Beats',
    artistId: 'artist4',
    duration: 215,
    coverUrl: 'https://picsum.photos/300/300?random=13',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    genre: 'Hip-Hop',
  },
  {
    id: '14',
    title: 'Silent Night',
    artist: 'Nature Sounds',
    artistId: 'artist5',
    duration: 380,
    coverUrl: 'https://picsum.photos/300/300?random=14',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    genre: 'Ambient',
  },
  {
    id: '15',
    title: 'Future Sounds',
    artist: 'Aurora Waves',
    artistId: 'artist1',
    duration: 255,
    coverUrl: 'https://picsum.photos/300/300?random=15',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    genre: 'Ambient',
  },
];

export const MOCK_ARTISTS: Artist[] = [
  {
    id: 'artist1',
    name: 'Aurora Waves',
    bio: 'Creating ethereal soundscapes that transport you beyond reality.',
    followers: 125000,
    photoUrl: 'https://picsum.photos/200/200?random=101',
    tracks: MOCK_TRACKS.filter((t) => t.artistId === 'artist1'),
  },
  {
    id: 'artist2',
    name: 'Neon Lights',
    bio: 'Fusing electronic and modern pop for unforgettable experiences.',
    followers: 98000,
    photoUrl: 'https://picsum.photos/200/200?random=102',
    tracks: MOCK_TRACKS.filter((t) => t.artistId === 'artist2'),
  },
  {
    id: 'artist3',
    name: 'Synthetic Echo',
    bio: 'Masters of synthwave and retro-futuristic sounds.',
    followers: 87000,
    photoUrl: 'https://picsum.photos/200/200?random=103',
    tracks: MOCK_TRACKS.filter((t) => t.artistId === 'artist3'),
  },
  {
    id: 'artist4',
    name: 'City Beats',
    bio: 'Urban rhythms and hip-hop culture meets modern production.',
    followers: 156000,
    photoUrl: 'https://picsum.photos/200/200?random=104',
    tracks: MOCK_TRACKS.filter((t) => t.artistId === 'artist4'),
  },
  {
    id: 'artist5',
    name: 'Nature Sounds',
    bio: 'Capturing the essence of nature in peaceful compositions.',
    followers: 201000,
    photoUrl: 'https://picsum.photos/200/200?random=105',
    tracks: MOCK_TRACKS.filter((t) => t.artistId === 'artist5'),
  },
];

export const FEATURED_TRACKS = MOCK_TRACKS.slice(0, 5);
